### ISSUE TITLE
can not access the local installation through localhost:8080/doc2hpo

### ISSUE THREAD

**Issue by lis262** [stormliucong/doc2hpo#17]
Hello,
I followed the instructions to install the doc2hpo. All the steps were successful until the last step, when I visit localhost:8080/doc2hpo, it shows status 404 not found.
I checked the log file of tomcat, it seems the spring platform is not on the classpath:

> `06-Feb-2020 14:34:47.631 INFO [localhost-startStop-1] org.apache.catalina.core.A
> pplicationContext.log No Spring WebApplicationInitializer types detected on clas
> spath
> 06-Feb-2020 14:34:47.818 INFO [localhost-startStop-1] org.apache.catalina.core.A
> pplicationContext.log Initializing Spring root WebApplicationContext
> 06-Feb-2020 14:34:49.255 SEVERE [localhost-startStop-1] org.apache.catalina.core
> .StandardContext.listenerStart Exception sending context initialized event to li
> stener instance of class [org.springframework.web.context.ContextLoaderListener]
>  org.springframework.beans.factory.BeanCreationException: Error creating bean wi
> th name 'parseController': Invocation of init method failed; nested exception is
>  java.lang.NullPointerException`

I tried to download the binary spring-framework-5.2.3.RELEASE, and add the path to tomcat classpath, still doesn't work. Am I missing anything? Thanks

**Comment by stormliucong** [comment]
Did you use eclipse to build the project? Could you provide more details?

-- OS system
-- JDK version
-- tomcat version
-- maven version

**Comment by lis262** [comment]
No, I didn't use eclipse. I directly used maven to build the war file as described in the documentation. -- OS: Redhat 7.6
-- JDK: 1.8.0_221
-- tomcat: 8.5.35
-- maven: 3.6.3.
I'll try to use eclipse to build the war file and see how it goes. Thanks

**Comment by stormliucong** [comment]
Thanks for reporting the issue. 
I will look into the issue and try to get it back to you.

**Comment by stormliucong** [comment]
Hi, I think I have fixed the bug. I forget to update the config.properties_bak file.
I also updated the readme file. Please see  ### Step 2: Configuration of Doc2Hpo [subsection 3].
You have to set the path correctly in the config.properties and change the name of config.properties_bak to config.properties. Let me know if the error is gone

**Comment by stormliucong** [comment]
I found I forget to update the config file. Please 
I have updated the github.

**Comment by lis262** [comment]
Thanks very much. That solution works, now I can access the webpage.

But I have an other problem. In the webpage, if I click example, it doesn't import the patient's description in the mm_note.txt. And the submit button doesn't work either (should I open another issue for this question?).

**Comment by stormliucong** [comment]
That's a great catch. We actually had this bug before, but somehow we were unable to reproduce the bug. It will be very helpful if you open a new issue
